# Generated by Django 3.1.1 on 2020-11-16 08:16

import detect.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('NT', 'NOT WANTED'), ('W', 'WANTED')], default='NOT WANTED', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='detect.person')),
                ('staff_id', models.CharField(max_length=255)),
            ],
            bases=('detect.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='detect.person')),
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('faculty', models.CharField(choices=[('BA', 'Business Administration'), ('ED', 'Education'), ('T', 'Theology'), ('IT', 'Information Technology')], max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
            bases=('detect.person',),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to=detect.models.get_upload_to)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect.person')),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('SO', 'Solved'), ('UI', 'Under Investigation')], default='Under Investigation', max_length=100)),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='detect.person')),
            ],
        ),
    ]
