# Generated by Django 3.1.7 on 2021-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='crime_type',
            field=models.CharField(choices=[('Phone Robbery', 'Phone Robbery'), ('Cabble Robbery', 'Cabble Robbery'), ('Computer Robbery', 'Computer Robbery')], default='Phone robbery', max_length=100),
        ),
    ]
