# Generated by Django 3.1.1 on 2021-01-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='status',
            field=models.CharField(choices=[('Under Investigation', 'Under Investigation'), ('Solved', 'Solved')], default='Under Investigation', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('NOT WANTED', 'NOT WANTED'), ('WANTED', 'WANTED')], default='NOT WANTED', max_length=100),
        ),
    ]
