# Generated by Django 3.1.5 on 2021-02-22 20:16

import detect.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(null='True', validators=[detect.models.validate_dob], verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='names',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[detect.models.validate_length]),
        ),
    ]
