# Generated by Django 3.1.7 on 2021-04-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Images',
        ),
    ]
