# Generated by Django 3.2.13 on 2022-04-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Not Wanted', 'Not Wanted'), ('Wanted', 'Wanted')], default='Not Wanted', max_length=100),
        ),
    ]
