# Generated by Django 3.1.1 on 2020-12-09 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedCriminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('location', models.CharField(max_length=255)),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='detect.person')),
            ],
        ),
    ]
