# Generated by Django 3.1.5 on 2021-03-12 10:36

import detect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_auto_20210311_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='names',
            field=models.CharField(max_length=255, validators=[detect.models.validate_names]),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[detect.models.validate_mobile], verbose_name='Phone Number'),
        ),
    ]
