# Generated by Django 3.1.5 on 2021-03-16 11:22

import detect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_auto_20210312_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=15, validators=[detect.models.validate_mobile], verbose_name='Phone Number'),
        ),
    ]
