# Generated by Django 3.1.5 on 2021-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0004_auto_20210316_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
