# Generated by Django 3.1.5 on 2021-03-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0005_person_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
