# Generated by Django 3.1.5 on 2021-03-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0006_auto_20210316_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Investigation', 'Under Investigation'), ('Solved', 'Solved')], default='Pending', max_length=100),
        ),
    ]
