# Generated by Django 3.1.5 on 2021-03-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0007_auto_20210316_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='user',
        ),
        migrations.AddField(
            model_name='crime',
            name='comment',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='crime_type',
            field=models.CharField(choices=[('Phone Robbery', 'Phone Robbery'), ('cabble Robbery', 'cabble Robbery'), ('computer Robbery', 'computer Robbery')], default='Phone ro', max_length=100),
        ),
        migrations.AddField(
            model_name='crime',
            name='suspect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crime_suspect', to='detect.person'),
        ),
        migrations.AddField(
            model_name='crime',
            name='victim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crime_victim', to='detect.person'),
        ),
    ]
