# Generated by Django 3.1.5 on 2021-03-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0008_auto_20210317_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='crime_type',
            field=models.CharField(choices=[('Phone Robbery', 'Phone Robbery'), ('cabble Robbery', 'cabble Robbery'), ('computer Robbery', 'computer Robbery')], default='Phone robbery', max_length=100),
        ),
    ]
