# Generated by Django 3.1.5 on 2021-03-17 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0009_auto_20210317_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crime_victim', to='detect.person'),
        ),
    ]
