# Generated by Django 3.1.5 on 2021-02-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_auto_20210227_1327'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='person_ptr',
        ),
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.OneToOneField(db_column='person_id', default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='detect.person'),
            preserve_default=False,
        ),
    ]
